### ISSUE TITLE
App sometimes crashes, unable to establish a connection w/ DB

### ISSUE THREAD

**Issue by diego2013** [mdpnp/BigWallDisplay_1#2]
![image](https://cloud.githubusercontent.com/assets/4389491/14958089/dd6c57f6-1056-11e6-9509-dd4500f267ed.png)

the latest log
/Users/diego/.meteor/packages/meteor-tool/.1.3.1.1tiubdb++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:300
                        throw(ex);
                              ^
Error: failed to connect to [localhost:27017]
    at Object.Future.wait (/Users/diego/.meteor/packages/meteor-tool/.1.3.1.1tiubdb++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:420:15)
    at new MongoConnection (packages/mongo/mongo_driver.js:213:27)
    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
    at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
    at new Mongo.Collection (packages/mongo/collection.js:102:40)
    at meteorInstall.imports.api.patients.js (imports/api/patients.js:4:25)
    at fileEvaluate (packages/modules-runtime.js:158:9)
    at require (packages/modules-runtime.js:92:16)
    at meteorInstall.server.main.js (server/main.js:3:1)
    - - - - -
    at [object Object].<anonymous> (/Users/diego/.meteor/packages/npm-mongo/.1.4.42.1ybqvxj++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/server.js:556:74)
    at [object Object].emit (events.js:106:17)
    at [object Object].<anonymous> (/Users/diego/.meteor/packages/npm-mongo/.1.4.42.1ybqvxj++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:156:15)
    at [object Object].emit (events.js:98:17)
    at Socket.<anonymous> (/Users/diego/.meteor/packages/npm-mongo/.1.4.42.1ybqvxj++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
    at Socket.emit (events.js:95:17)
    at net.js:834:16
    at process._tickCallback (node.js:458:13)
Exited with code: 8
Your application is crashing. Waiting for file change.

**Comment by diego2013** [comment]
See [this link](https://github.com/meteor/meteor/issues/6872)

I'm on mongo version 3.0.X

![image](https://cloud.githubusercontent.com/assets/4389491/14958153/408eb11c-1057-11e6-8497-effef92889de.png)
